# Generated by Django 4.1.3 on 2023-07-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidade', models.FloatField()),
                ('temperatura_motor', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('pressao_oleo', models.FloatField()),
                ('tensao_bateria', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
