# Generated by Django 5.0.4 on 2024-04-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dados_gpsaltitude_dados_gpsspeed_dados_gpsx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='pressao_oleo',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='rpm',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='temperatura_motor',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='tensao_bateria',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='velocidade',
        ),
    ]
