# Generated by Django 5.0.4 on 2024-04-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dados_pressao_oleo_dados_rpm_dados_temperatura_motor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='velocidade',
        ),
    ]
